### ISSUE TITLE
Table produces errors when switching out rows.

### ISSUE THREAD

**Issue by HHlambda** [lustre-labs/lustre#134]
At a certain number of table rows errors happen when pressing a different button. I altered the "99-SERVER-COMPONENTS" example to reproduce. Only the 'counter.gleam' file was changed. If the first set of strings(first_string and second_string) are used its fine. The next set of strings produce different errors. "childNodes" error and  "remove" error.

[counter.txt](https://github.com/lustre-labs/lustre/files/15357931/counter.txt)

**Comment by JScearcy** [comment]
This looks like an issue in this example due to an older version of Lustre shipping an incompatible version of the server component runtime. After replicating this issue, bumping to the latest version resolved errors. I
PR open to update this example. In the meantime, if you update dependencies you can test that this resolves the issue locally as well.

**Comment by hayleigh-dot-dev** [comment]
Thank you for opening this issue (and being so patient with these bugs). I've just published `v4.2.3` which I think has fixed the source of this bug: it was down to Gleam's (lack of) ordering in dict keys. Could you give this new version a go and report back if things are fixed?

**Comment by HHlambda** [comment]
Will do, although I have to wait until work on Mon. Thanks as always for the fast response!

**Comment by HHlambda** [comment]
Everything looks good. No errors and the rows are changing out smoothly. Thanks!!
