### ISSUE TITLE
Quickstart app can not resolve lustre_dev_tools package

### ISSUE THREAD

**Issue by danbim** [lustre-labs/lustre#156]
Hej, I'm new to gleam and lustre and just ran the Lustre quickstart tutorial (https://hexdocs.pm/lustre/guide/01-quickstart.html). This fails fairly early when the package manager fails to resolve `lustre_dev_tools` due to incompatible version constraints in the dependency tree.

```
➜  pwa gleam new app && cd app && gleam add lustre
Your Gleam project app has been successfully created.
The project can be compiled and tested by running these commands:

	cd app
	gleam test

  Resolving versions
Downloading packages
 Downloaded 6 packages in 0.04s
      Added lustre v4.3.0
➜  app git:(main) ✗ code .
➜  app git:(main) ✗ gleam add --dev lustre_dev_tools
  Resolving versions
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to find compatible versions for the version constraints in your
gleam.toml. The conflicting packages are:

- app
- gleam_json
- wisp
- lustre_dev_tools
```

Coming from Scala (with Akka Actors and what was build on top/around it), what drove me to gleam is a type-safe language on the Beam VM/OTP AND a framework in the Phoenix LiveView spirit, a combination I was always waiting for.

The error message is not super helpful yet, I've been trying to figure out what to do manually but it's not trivial. Would be great if the quickstart app would work again and if the error message would be more helpful :).

**Comment by hayleigh-dot-dev** [comment]
Hey there! Yeah it's unfortunate that gleam is not so helpful here...

The problem is that a package `lustre_dev_tools` depends on, `wisp`, is using `gleam_json` v1.x but _lustre's_ `gleam_json` constraint is wider so you will have 2.x in your project after adding lustre.

You can resolve this manually by explicitly adding `gleam_json = "1.0.1"` as a dependency in your `gleam.toml` (and potentially deleting your `manifest.toml` if you get some complaints).

Actually you have come at the worst time. 24 hours ago the guide did indicate that you needed 1.0.1 explicitly (until the issue is resolved upstream) but I removed this part of the guide in anticipation for a patch release of Lustre that fixes the version itself, but then I caught a flight and have otherwise been occupied today 😅 

---

For some wider context, `gleam_json` is api-compatible across both v1 and v2 but v2 requires OTP 27 (on the erlang target, of course) hence the major version bump. Lustre has a constraint that is wide enough that users can use either version, but gleam will always grab the latest version in a fresh project.

I'm considering re-tightening that version constraint so Lustre is _also_ fixed at v1 until wisp updates upstream. [It has been indicated](https://github.com/gleam-wisp/wisp/pull/82#issuecomment-2214034564) that wisp won't be updated until _homebrew_ updates their erlang formula with OTP 27, and homebrew have indicated they won't do that because OTP 27 doesn't ship with manpages...

---

**Comment by danbim** [comment]
Hi Hayleigh! Thanks for giving me a tip and some context. I tried to follow the tip, ran into more dependency issues and then started from scratch. It works now, following the quick start guide :)
