### ISSUE TITLE
Wrapping server component view in `element.fragment` breaks DOM patching

### ISSUE THREAD

**Issue by JonasGruenwald** [lustre-labs/lustre#193]
Hiya!
I think I found a small issue with server components, not sure if this is something that's known already.

### Steps

* Using the server components example as a basis: https://github.com/lustre-labs/lustre/tree/main/examples/99-server-components
* Wrap the view function in `element.fragment([])`

```gleam
fn view(model: Model) -> Element(Msg) {
  let styles = [#("width", "100vw"), #("height", "100vh"), #("padding", "1rem")]
  let count = int.to_string(model)
  element.fragment([
    ui.centre(
      [attribute.style(styles)],
      ui.stack([], [
        ui.button([event.on_click(Incr)], [element.text("+")]),
        html.slot([]),
        html.p([attribute.style([#("text-align", "center")])], [
          element.text(count),
        ]),
        ui.button([event.on_click(Decr)], [element.text("-")]),
      ]),
    ),
  ])
}

```
* Run the application and visit the page in the browser

### What happens
The server component is rendered but not interactive, when clicking the buttons the following error is logged to the browser console:

```js
Uncaught TypeError: Cannot read properties of null (reading 'childNodes')
    at getDeepChild (lustre-server-component.mjs:318:19)
    at patch (lustre-server-component.mjs:57:18)
    at #diff (lustre-server-component.mjs:566:5)
    at LustreServerComponent.messageReceivedCallback (lustre-server-component.mjs:498:26)
    at WebSocket.<anonymous> (lustre-server-component.mjs:488:31)
getDeepChild @ lustre-server-component.mjs:318
patch @ lustre-server-component.mjs:57
#diff @ lustre-server-component.mjs:566
messageReceivedCallback @ lustre-server-component.mjs:498
(anonymous) @ lustre-server-component.mjs:488
```

**Comment by hayleigh-dot-dev** [comment]
Ah no, how frustrating! I think we've had problems with fragments and server components in the past. I'm in the middle of a move of country at the moment so my bandwidth to fix things is a bit limited, but I'll see if I can solve it soon!

**Comment by JonasGruenwald** [comment]
Ah yeah no rush with this at all!
I ended up not needing the `element.fragment` anyways for what I'm working on but had left it my view in by accident and noticed things stopped working.

**Comment by eliknebel** [comment]
I also ran into a similar case of this error while trying out server components.

Here is another snippet of code that will throw the error:
```
fn view(model: Model) -> Element(Msg) {
  let count = int.to_string(model)

  div([], [
    h1([], []),
    nav([], []),
    ]),
    element.fragment([div([], []), div([], [])]),
    div([], [
      button([event.on_click(Decrement)], [text("-")]),
      span([], [element.text(count)]),
      button([event.on_click(Increment)], [text("+")]),
    ]),
  ])
}
```

Which creates a patch `[[["0-3-1-0",{"content":"3"}]],[],[]]` to update the count in the div > div > span > text(count). But the actual DOM looks like:
```
  div
    h1
    nav
    div   <- inserted by fragment
    div   <- inserted by fragment
    div
      button
      span
      button
```
Which would indicate that a patch of `[[["0-4-1-0",{"content":"3"}]],[],[]]` is actually required to locate and update the correct DOM element.

Digging into the code, it seems like the patcher is generating a key that expects the fragment element to exist in the client vdom, but because the morph function unshifts a fragment's child elements directly into the dom, the concept of a fragment element existing gets lost and the patch is effectively trying to drill into the wrong element.

I'm not sure what the best fix would be here though, either the client needs to somehow retain the concept of a fragment so that a patch can be properly applied, or the patch needs to take into account fragments when generating the key, and possibly adjust it based on the number of sibling elements generated by the fragment preceding a node that is being patched.

**Comment by hayleigh-dot-dev** [comment]
> either the client needs to somehow retain the concept of a fragment so that a patch can be properly applied

Yeah we can do this!

**Comment by hayleigh-dot-dev** [comment]
Closing as Lustre now no longer needs special runtime support for fragments, instead fragments are simple custom elements with `display: contents;` so they don't affect layouting.
