### ISSUE TITLE
Quickstart example doesn't compile anymore

### ISSUE THREAD

**Issue by vacmar01** [lustre-labs/lustre#228]
I'm new to gleam and lustre and I wanted to try out the quickstart guide. Unfortunately it doesn't compile anymore. 

`glearray` as a dependency of lustre needs the `Iterator` type from `gleam/iterator` but this module was deprecated in version 0.5 of the `gleam_stdlib`. 

What is the easiest way for me to circumvent this dependency problem right now?

**Comment by escherize** [comment]
I am hitting this as well. I think Iterator was deprecated, as the hex docs for it are gone, too

**Comment by vacmar01** [comment]
What I did was downgrading lustre and the standard lib to 4.6.0 and 0.42 respectively. This worked.

**Comment by hayleigh-dot-dev** [comment]
Hey there thanks for the issue. This is actually nothing to do with lustre, the problem is like this:
- lustre_dev_tools depends on spinner
- spinner depends on glearray
- glearray has not been updated since may.

I will update [dev-tools](https://github.com/lustre-labs/dev-tools) to remove this dependency and everything should be fine.
